services:
  postgres:
    image: postgres:17
    container_name: PostgresLaravel
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE:-Youvento}
      POSTGRES_USER: ${DB_USERNAME:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-user_password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data
    networks:
      - laravel_network

  app:
    build:
      context: .
      dockerfile: Docker/Dockerfile
    container_name: laravel_app
    restart: always 
    volumes:
      - ./project:/var/www/html
    ports:
      - "80:80"  
    depends_on:
      - postgres
    networks:
      - laravel_network
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: ${DB_DATABASE:-Youvento}
      DB_USERNAME: ${DB_USERNAME:-user}
      DB_PASSWORD: ${DB_PASSWORD:-user_password}
      APP_ENV: ${APP_ENV:-production}
      APP_DEBUG: ${APP_DEBUG:-false}
      APP_URL: ${APP_URL:-http://localhost}

volumes:
  postgres_db:
  
networks:
  laravel_network: